### ISSUE TITLE
CDK version >=1.36.0 <=1.38.0 may encounter the issue 

### ISSUE THREAD

**Issue by lanzi0907** [MoonsetJS/Moonset#45] opened 2020-05-21 02:36 UTC
Do not need us to resolve.
Just keep a note here for reference.
If the CDK version is in the range as title, if we meet "MoonsetStepFunctionStack failed: Error: This stack uses assets, so the toolkit stack must be deployed to the environment (Run "cdk bootstrap aws://713790767987/us-east-1")" when we do Moonset deploy, run Run "cdk bootstrap aws://713790767987/us-east-1" is required.
And it will fail with "--app is required either in command-line, in cdk.json or in ~/.cdk.json"
It's an AWS CDK issue:
cdk bootstrap cannot be used without supplying the --app argument #7970
https://github.com/aws/aws-cdk/issues/7906

Upgrade CDK version to 1.39.0 will resolve it.

**Comment by wangzhihao** [comment] 2020-05-24 08:23
Upgrade to v1.41.0 at https://github.com/MoonsetJS/Moonset/pull/48 . Please verify if the issue is resolved.

**Comment by wangzhihao** [comment] 2020-08-25 07:44
Verified. It's fixed now.

**Closed by wangzhihao** 2020-08-25 07:44 UTC
